/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import controllers.Controller;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Matias
 */
public class VistaPrincipal extends javax.swing.JFrame {
        private DefaultTableModel modeloChica = new DefaultTableModel();

    public DefaultTableModel getModeloChica() {
        return modeloChica;
    }

    public void seTModeloChica(DefaultTableModel modeloChica) {
        this.modeloChica = modeloChica;
    }

    private DefaultTableModel modeloGrande = new DefaultTableModel();

    public DefaultTableModel getModeloGrande() {
        return modeloGrande;
    }

    public void seTModeloGrande(DefaultTableModel modeloGrande) {
        this.modeloGrande = modeloGrande;
    }

    public JTable getTableGrande() {
        return TablaGrande;
    }

    public void setTableGrande(JTable tablagrande) {
        this.TablaGrande = tablagrande;
    }

    public JTable getTableChica() {
        return TablaChica;
    }

    public void setTableChica(JTable tablachica) {
        this.TablaChica = tablachica;
    }

    public void setProfesor(JTextField profesor) {
        this.TextProfesor = profesor;
    }

    public JTextField getProfesor() {
        return TextProfesor;
    }

    public void setMateria(JTextField materia) {
        this.TextMateria = materia;
    }

    public JTextField getMateria() {
        return TextMateria;
    }

    public void setAlumno(JTextField alumno) {
        this.TextAlumno = alumno;
    }

    public JTextField getAlumno() {
        return TextAlumno;
    }

    public void setLegajo(JTextField legajo) {
        this.TextLegajo = legajo;
    }

    public JTextField getLegajo() {
        return TextLegajo;
    }

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSalir = new javax.swing.JButton();
        BtnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextProfesor = new javax.swing.JTextField();
        TextMateria = new javax.swing.JTextField();
        TextLegajo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaGrande = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaChica = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        TextAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir(evt);
            }
        });
        getContentPane().add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        BtnCrear.setText("Crear");
        BtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrear(evt);
            }
        });
        getContentPane().add(BtnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, -1, -1));

        jLabel1.setText("Legajo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setText("Profesor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setText("Materia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        getContentPane().add(TextProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 100, -1));
        getContentPane().add(TextMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, -1));
        getContentPane().add(TextLegajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, -1));

        TablaGrande.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Alumno", "Legajo"
            }
        ));
        TablaGrande.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                none(evt);
            }
        });
        jScrollPane2.setViewportView(TablaGrande);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 420, 180));

        TablaChica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

                {null, null, null}

            },
            new String [] {
                "Fecha", "Profesor", "Materia"
            }
        ));
        jScrollPane1.setViewportView(TablaChica);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 230, 40));

        jLabel5.setText("Alumno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
        getContentPane().add(TextAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnSalir

    private void BtnCrear(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrear
        // TODO add your handling code here:
        Controller.planillaGrande(this);
       
        Controller.FormatoTablaChica(this);
        Controller.FromatoTablaGrande(this);


    }//GEN-LAST:event_BtnCrear

    private void none(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none
    public void VistaMain() {

        initComponents();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrear;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTable TablaChica;
    private javax.swing.JTable TablaGrande;
    private javax.swing.JTextField TextAlumno;
    private javax.swing.JTextField TextLegajo;
    private javax.swing.JTextField TextMateria;
    private javax.swing.JTextField TextProfesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
